[package]
name = "autoitv3-deobf"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
autoitv3-i18n = { path = "../autoitv3-i18n" }
autoitv3-ast = { path = "../autoitv3-ast" }
autoitv3-runtime = { path = "../autoitv3-runtime" }
autoitv3-platform = { path = "../autoitv3-platform" }

[dev-dependencies]
autoitv3-format = { path = "../autoitv3-format" }

[lints.rust]
unused = "warn"
